services:
  mariadb:
    image: mariadb:11.4
    command: [
      "mariadbd",
      "--max-connections=120",
      "--innodb-buffer-pool-size=128M",
      "--innodb-log-file-size=32M",
      "--performance-schema=OFF"
    ]
    environment:
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY:?Set APP_KEY in .env before running docker compose}
      DB_CONNECTION: mariadb
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: appdb
      DB_USERNAME: appuser
      DB_PASSWORD: apppass
      DONATIONS: ${DONATIONS:-off}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8085:80"
    volumes:
      - frontend_storage:/var/www/html/storage
      - ./frontend/.env:/var/www/html/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mariadb
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
      LOG_LEVEL: INFO
      RETENTION_WEEKS: "5"
      BLOCK_TIME_SECONDS: "18"
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
  frontend_storage:
